export const mockLogBookData = {
  totalRecords: 17,
  currentPage: 1,
  recordsPerPage: 9,
  totalPages: 2,
  data: [
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "100",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "600",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "2000",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "290",
      previousWeekOSAPercentage: "140",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodrants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "12 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
    {
      storeName: "C&C",
      category: "Deodorants",
      actionPerformed: "Increase Core OSA in Deodorants category",
      currentOSAPercentage: "200",
      previousWeekOSAPercentage: "400",
      salesUpliftNumber: "200",
      actionCreatedOn: "11 Jan, 2022",
      actionCompletedOn: "12 Jan, 2022",
      completedBy: "Raunak Sachdeva",
      assignedTo: "Gursimran Singh",
    },
  ],
};
