export const nestedOSaTableData = {
  totalRecords: 6,
  currentPage: 1,
  recordsPerPage: 3,
  totalPages: 2,
  data: [
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 1,
    },
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 2,
    },
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 3,
    },
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 4,
    },
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 5,
    },
    {
      category: "Deodorants",
      action: "Increase Core OSA in KPI",
      currentOSAPercentage: "200",
      targetOSAPercentage: "100",
      salesUpliftNumber: "200",
      fullOSAPercentage: "200",
      actionCreatedOn: "12 Jan, 2022",
      reasonForNonCompliance: "Increase Core OSA in Deodrant Category",
      fieldRep: "Raunak Sachdeva",
      status: "fixed",
      actionId: 6,
    },
  ],
};
